In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the   vocabulary size
voc_size=10000

In [5]:
### One hot representation for every word
one_hot_repr=[one_hot(words, voc_size)for words in sent]
one_hot_repr

[[4378, 2563, 4948, 3585],
 [4378, 2563, 4948, 7583],
 [4378, 8684, 4948, 6810],
 [8179, 4190, 7800, 1870, 2091],
 [8179, 4190, 7800, 1870, 3419],
 [3163, 4378, 9233, 4948, 6575],
 [1605, 6011, 7568, 1870]]

In [7]:
## Word Embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences # it is used to convert sentences to similar size
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4378 2563 4948 3585]
 [   0    0    0    0 4378 2563 4948 7583]
 [   0    0    0    0 4378 8684 4948 6810]
 [   0    0    0 8179 4190 7800 1870 2091]
 [   0    0    0 8179 4190 7800 1870 3419]
 [   0    0    0 3163 4378 9233 4948 6575]
 [   0    0    0    0 1605 6011 7568 1870]]


In [9]:
## feature representation
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile("adam", "mse")

/Users/chandanjha/Documents/ann_classification/cenv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step


array([[[ 4.90217693e-02, -3.94083038e-02, -4.17440161e-02,
         -3.57590690e-02,  1.40232332e-02, -3.49494442e-02,
          4.86414321e-02, -3.97106037e-02, -2.95074116e-02,
         -3.88763174e-02],
        [ 4.90217693e-02, -3.94083038e-02, -4.17440161e-02,
         -3.57590690e-02,  1.40232332e-02, -3.49494442e-02,
          4.86414321e-02, -3.97106037e-02, -2.95074116e-02,
         -3.88763174e-02],
        [ 4.90217693e-02, -3.94083038e-02, -4.17440161e-02,
         -3.57590690e-02,  1.40232332e-02, -3.49494442e-02,
          4.86414321e-02, -3.97106037e-02, -2.95074116e-02,
         -3.88763174e-02],
        [ 4.90217693e-02, -3.94083038e-02, -4.17440161e-02,
         -3.57590690e-02,  1.40232332e-02, -3.49494442e-02,
          4.86414321e-02, -3.97106037e-02, -2.95074116e-02,
         -3.88763174e-02],
        [ 2.82433294e-02,  1.68200582e-03, -1.62346959e-02,
          4.88132499e-02,  4.87109758e-02,  2.54958384e-02,
         -5.16790152e-03, -2.98323166e-02, -4.775674

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 4378, 2563, 4948, 3585], dtype=int32)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[[ 4.90217693e-02, -3.94083038e-02, -4.17440161e-02,
         -3.57590690e-02,  1.40232332e-02, -3.49494442e-02,
          4.86414321e-02, -3.97106037e-02, -2.95074116e-02,
         -3.88763174e-02],
        [ 4.90217693e-02, -3.94083038e-02, -4.17440161e-02,
         -3.57590690e-02,  1.40232332e-02, -3.49494442e-02,
          4.86414321e-02, -3.97106037e-02, -2.95074116e-02,
         -3.88763174e-02],
        [ 4.90217693e-02, -3.94083038e-02, -4.17440161e-02,
         -3.57590690e-02,  1.40232332e-02, -3.49494442e-02,
          4.86414321e-02, -3.97106037e-02, -2.95074116e-02,
         -3.88763174e-02],
        [ 4.90217693e-02, -3.94083038e-02, -4.17440161e-02,
         -3.57590690e-02,  1.40232332e-02, -3.49494442e-02,
          4.86414321e-02, -3.97106037e-02, -2.95074116e-02,
         -3.88763174e-02],
        [ 2.82433294e-02,  1.68200582e-03, -1.62346959e-02,
          4.88132499e-02,  4.87109758e-02,  2.54958384e-02,
         -5.16790152e-03, -2.98323166e-02, -4.775674